config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get 'welcome/index'
  
  resources :occupations
  resources :children
  resources :fathers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/child.rb
class Child < ApplicationRecord
  belongs_to :father
end

app/models/father.rb
class Father < ApplicationRecord
  has_many :children
  belongs_to :occupation

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

#  def teste
#   "teste teste"
#  end

  def occupation_description
    if self.occupation.blank?
      " - "
    else
      self.occupation.description
    end
  end

end

app/models/occupation.rb
class Occupation < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  before_action :set_child, only: %i[ show edit update destroy ]
  before_action :set_father, only: %i[ edit update new ]

  # GET /children or /children.json
  def index
    @children = Child.all
  end

  # GET /children/1 or /children/1.json
  def show
  end

  # GET /children/new
  def new
    @child = Child.new
    @fathers = Father.all
  end

  # GET /children/1/edit
  def edit
    @fathers = Father.all
  end

  # POST /children or /children.json
  def create
    @child = Child.new(child_params)

    respond_to do |format|
      if @child.save
        format.html { redirect_to child_url(@child), notice: "Child was successfully created." }
        format.json { render :show, status: :created, location: @child }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @child.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /children/1 or /children/1.json
  def update
    respond_to do |format|
      if @child.update(child_params)
        format.html { redirect_to child_url(@child), notice: "Child was successfully updated." }
        format.json { render :show, status: :ok, location: @child }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @child.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /children/1 or /children/1.json
  def destroy
    @child.destroy

    respond_to do |format|
      format.html { redirect_to children_url, notice: "Child was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_child
      @child = Child.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def child_params
      params.require(:child).permit(:name, :sex, :father_id)
    end

    def set_father
      @fathers = Father.all
    end
end

app/controllers/fathers_controller.rb
class FathersController < ApplicationController
  before_action :set_father, only: %i[ show edit update destroy ]
  before_action :set_occupations, only: %i[ new update create edit ]

  # GET /fathers or /fathers.json
  def index
    @fathers = Father.all
  end

  # GET /fathers/1 or /fathers/1.json
  def show
  end

  # GET /fathers/new
  def new
    @father = Father.new
  end

  # GET /fathers/1/edit
  def edit
  end

  # POST /fathers or /fathers.json
  def create
    @father = Father.new(father_params)

    respond_to do |format|
      if @father.save
        format.html { redirect_to father_url(@father), notice: "Father was successfully created." }
        format.json { render :show, status: :created, location: @father }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @father.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fathers/1 or /fathers/1.json
  def update
    respond_to do |format|
      if @father.update(father_params)
        format.html { redirect_to father_url(@father), notice: "Father was successfully updated." }
        format.json { render :show, status: :ok, location: @father }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @father.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fathers/1 or /fathers/1.json
  def destroy
    @father.destroy

    respond_to do |format|
      format.html { redirect_to fathers_url, notice: "Father was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_father
      @father = Father.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def father_params
      params.require(:father).permit(:name, :cpf, :email, :occupation_id, :avatar)
    end

    def set_occupations
      @occupations = Occupation.all
    end
end

app/controllers/occupations_controller.rb
class OccupationsController < ApplicationController
  before_action :set_occupation, only: %i[ show edit update destroy ]

  # GET /occupations or /occupations.json
  def index
    @occupations = Occupation.all
  end

  # GET /occupations/1 or /occupations/1.json
  def show
  end

  # GET /occupations/new
  def new
    @occupation = Occupation.new
  end

  # GET /occupations/1/edit
  def edit
  end

  # POST /occupations or /occupations.json
  def create
    @occupation = Occupation.new(occupation_params)

    respond_to do |format|
      if @occupation.save
        format.html { redirect_to occupation_url(@occupation), notice: "Occupation was successfully created." }
        format.json { render :show, status: :created, location: @occupation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @occupation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /occupations/1 or /occupations/1.json
  def update
    respond_to do |format|
      if @occupation.update(occupation_params)
        format.html { redirect_to occupation_url(@occupation), notice: "Occupation was successfully updated." }
        format.json { render :show, status: :ok, location: @occupation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @occupation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /occupations/1 or /occupations/1.json
  def destroy
    @occupation.destroy

    respond_to do |format|
      format.html { redirect_to occupations_url, notice: "Occupation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_occupation
      @occupation = Occupation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def occupation_params
      params.require(:occupation).permit(:description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def pegar_sexo(sex)
    html = ""
    if sex == 'M'
      html = "Masculino"
    elsif sex == 'F'
      html = "Feminino"
    end
  end
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/fathers_helper.rb
module FathersHelper
end

app/helpers/occupations_helper.rb
module OccupationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/children/_form.html.erb
<%= form_with(model: child, local: true) do |form| %>
  <% if child.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(child.errors.count, "error") %> prohibited this child from being saved:</h2>

      <ul>
      <% child.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :child_name %>
    
  </div>

  <div class="field">
    <%= form.label :sex %>
    <%#= form.text_field :sex, id: :child_sex %>
    <%= form.select(:sex, 
              options_for_select([["Masculino", "M"], ["Feminino", "F"]], @child.sex), 
              {include_blank: "Selecione"}) 
    %>
  </div>

  <div class="field">
    <%= form.label :father_id %>
    <%#= form.text_field :father_id, id: :child_father_id %>
    <%= form.collection_select(:father_id, @fathers, :id, :name, include_blank: true) %>
    
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/children/edit.html.erb
<h1>Editing Child</h1>

<%= render 'form', child: @child %>

<%= link_to 'Show', @child %> |
<%= link_to 'Back', children_path %>

app/views/children/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Children</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Sex</th>
      <th>Father</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @children.each do |child| %>
      <tr>
        <td><%= child.name %></td>
        <td><%= child.sex %></td>
        <td><%= child.father.name %></td>
        <td><%= link_to 'Show', child %></td>
        <td><%= link_to 'Edit', edit_child_path(child) %></td>
        <td><%= link_to 'Destroy', child, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Child', new_child_path %>

app/views/children/new.html.erb
<h1>New Child</h1>

<%= render 'form', child: @child %>

<%= link_to 'Back', children_path %>

app/views/children/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @child.name %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @child.sex %>
</p>

<p>
  <strong>Father:</strong>
  <%= @child.father.name %>
</p>

<%= link_to 'Edit', edit_child_path(@child) %> |
<%= link_to 'Back', children_path %>

app/views/fathers/_form.html.erb
<%= form_with(model: father, html: { multipart: true }) do |form| %>
  <% if father.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(father.errors.count, "error") %> prohibited this father from being saved:</h2>

      <ul>
      <% father.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :avatar %>
    <%= form.file_field :avatar %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :father_name %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :occupation_id %>
    <%= form.collection_select(:occupation_id, @occupations, :id, :description, include_blank: true) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fathers/edit.html.erb
<h1>Editing Father</h1>

<%= render 'form', father: @father %>

<%= link_to 'Show', @father %> |
<%= link_to 'Back', fathers_path %>

app/views/fathers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fathers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>CPF</th>
      <th>Email</th>
      <th>Occupation</th>
      <!-- <th>Teste</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fathers.each do |father| %>
      <tr>
        <td><%= father.name %></td>
        <td><%= father.cpf %></td>
        <td><%= father.email %></td>
        <td><%= father.occupation_description %></td>
        <!-- <td><%#= father.teste %></td> -->
        <td><%= link_to 'Show', father %></td>
        <td><%= link_to 'Edit', edit_father_path(father) %></td>
        <td><%= link_to 'Destroy', father, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Father', new_father_path %>

app/views/fathers/new.html.erb
<h1>New Father</h1>

<%= render 'form', father: @father %>

<%= link_to 'Back', fathers_path %>

app/views/fathers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @father.name %>

  <strong>Cpf:</strong>
  <%= @father.cpf %>

  <strong>Email:</strong>
  <%= @father.email %>

  <strong>Occupation:</strong>
  <%= @father.occupation_description %>
  <hr>

  <strong>Avatar:</strong>
  <%= image_tag @father.avatar.url(:thumb) %>
  <hr>
  
</p>

  <ul>
  <% @father.children.each do |child| %>
    <li><%= "#{child.name} - #{pegar_sexo(child.sex)}" %></li>
  <% end%>
  </ul>




<%= link_to 'Edit', edit_father_path(@father) %> |
<%= link_to 'Back', fathers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Associations</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/occupations/_form.html.erb
<%= form_with(model: occupation, local: true) do |form| %>
  <% if occupation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(occupation.errors.count, "error") %> prohibited this occupation from being saved:</h2>

      <ul>
      <% occupation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :occupation_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/occupations/edit.html.erb
<h1>Editing Occupation</h1>

<%= render 'form', occupation: @occupation %>

<%= link_to 'Show', @occupation %> |
<%= link_to 'Back', occupations_path %>

app/views/occupations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Occupations</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @occupations.each do |occupation| %>
      <tr>
        <td><%= occupation.description %></td>
        <td><%= link_to 'Show', occupation %></td>
        <td><%= link_to 'Edit', edit_occupation_path(occupation) %></td>
        <td><%= link_to 'Destroy', occupation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Occupation', new_occupation_path %>

app/views/occupations/new.html.erb
<h1>New Occupation</h1>

<%= render 'form', occupation: @occupation %>

<%= link_to 'Back', occupations_path %>

app/views/occupations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @occupation.description %>
</p>

<%= link_to 'Edit', edit_occupation_path(@occupation) %> |
<%= link_to 'Back', occupations_path %>

app/views/welcome/index.html.erb
<h1>Welcome!</h1>
<p><%= link_to "Fathers", fathers_path %></p>
<p><%= link_to "Children", children_path %></p>
<p><%= link_to "Occupations", occupations_path %></p>

<!-- 
ANOTAÇÕES: 

Em: http://localhost:3000/rails/info/routes#, na parte de Helper (Path / Url)

occupation_path	GET	/occupations/:id(.:format) occupations#show <= no SINGULAR é o 'show'

occupations_path	GET	/occupations(.:format)	occupations#index
children_path	GET	/children(.:format)	children#index
fathers_path	GET	/fathers(.:format)	fathers#index

Portanto, o link_to se conecta as páginas index de cada controller
-->